# Dependencies
#markdown:            redcarpet
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false

# Permalinks
permalink:           /blog/:title/

# Setup
title:               Tjelvar Olsson
tagline:             'using computers to do better science'
url:                 http://tjelvarolsson.com
paginate:            1
baseurl:             /

author:
  name:              Tjelvar Olsson
  url:               https://twitter.com/tjelvar_olsson

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/tjelvar-olsson/tjelvar-olsson.github.io

# List of pages to include in the header of the website
pages_list:
  About:            '/about/'
  Posts:            '/posts/'
  Feed:             '/atom.xml'

# Allow URL redirects.
# See also: https://help.github.com/articles/redirects-on-github-pages/
gems:
  - jekyll-paginate
  - jekyll-redirect-from
